version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: translation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: translation_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  translation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://translation-mysql:3306/translation_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8082:8082"

volumes:
  mysql-data: